[package]
name = "kotonoha"
version = "0.1.0"
authors = ["Keishi Kawada <megumish@exploitouri.st>"]
edition = "2018"

[dependencies]
futures = "=0.1.28"

[features]
default = ["channel", "log"]

log = []

channel = ["log"]
