@startuml
title Deploy with Wording
autonumber

boundary WordingApp
entity Wording
database ExecutionWordingRepository

boundary ExecutorApp

box WordingDomain
    participant WordingApp
    participant Wording
    participant ExecutionWordingRepository
end box

box PakcageDomain
    participant ExecutorApp
end box

--> WordingApp: ExecutorName,WorkingDirectory
WordingApp --> ExecutorApp : ExecutorName,WorkingDirectory
WordingApp <-- ExecutorApp : Ok(Vec<Execution>)
note right: Prepare Execution
WordingApp --> Wording: ExecutionName,...etc
WordingApp <-- Wording: ExecutionWording
note right: New ExecutionWording
WordingApp --> ExecutionWordingRepository : ExecutionWording
WordingApp <-- ExecutionWordingRepository : Ok(ExecutionWording)
note right: Content of ExecutionWording
<-- WordingApp: Ok(ExecutionWording)


@enduml