@startuml
title New Executor
autonumber

boundary WordingApp
entity Wording
database ExecutorWordingRepository

boundary ExecutorApp

box WordingDomain
    participant WordingApp
    participant Wording
    participant ExecutorWordingRepository
end box

box PakcageDomain
    participant ExecutorApp
end box

--> WordingApp: ExecutorName,WorkingDirectory
WordingApp --> ExecutorApp : ExecutorName,WorkingDirectory
WordingApp <-- ExecutorApp : Ok(Executor)
note right: New Executor
WordingApp --> Wording : Executor
WordingApp <-- Wording : Log
note right: Generate Log from Executor
WordingApp --> LogRepository : Log
WordingApp <-- LogRepository : Ok(Log)
note right: push Log
<-- WordingApp: Ok(Log)

@enduml