@startuml
title Run WordingDaemon
autonumber

boundary WordingApp
control RunWordingDaemonService

box WordingDomain
    participant WordingApp
    participant RunWordingDaemonService
end box

--> WordingApp : ()
WordingApp --> RunWordingDaemonService : ()
WordingApp <-- RunWordingDaemonService : Ok(())
<-- WordingApp : Ok(())

@enduml
