@startuml
title ドメイン依存関係図

frame Libraries {

    package Kotonoha {
        cloud KotonohaDaemonDomain
        cloud LogDomain
    
        KotonohaDaemonDomain *-- LogDomain
    }
    interface LogApp
    interface KotonohaDaemonApp
    interface KotonohaIntegralApp
    LogApp *-- LogDomain
    KotonohaDaemonApp *-- KotonohaDaemonDomain
    KotonohaIntegralApp *-- LogApp
    KotonohaIntegralApp *-- KotonohaDaemonApp
    component LogAppSimpleImpl
    node KotonohaDaemonAppStdoutImpl
    note top of KotonohaDaemonAppStdoutImpl: Output Log into Stdout Daemon App
    LogAppSimpleImpl *-- LogApp
    KotonohaDaemonAppStdoutImpl *-- KotonohaDaemonApp
    component LogAppTestImpl
    component KotonohaDaemonAppTestImpl
    component KotonohaIntegralAppTestImpl
    LogAppTestImpl *-- LogApp
    KotonohaDaemonAppTestImpl *-- KotonohaDaemonApp
    KotonohaIntegralAppTestImpl *-- KotonohaIntegralApp
    package KotonohaAppTests {
        component LogAppTest
        component KotonohaDaemonAppTest
        component KotonohaIntegralAppTest
    
        LogAppTest *-- LogAppTestImpl
        KotonohaDaemonAppTest *-- KotonohaDaemonAppTestImpl
        KotonohaIntegralAppTest *-- KotonohaIntegralAppTestImpl
    }
    
    package DotIza {
        cloud DotIzaDaemonDomain
        cloud ModuleDomain
    
        ModuleDomain *-- LogApp
        DotIzaDaemonDomain *-- ModuleDomain
    }
    interface ModuleApp
    interface DotIzaDaemonApp
    interface DotIzaIntegralApp
    ModuleApp *-- ModuleDomain
    DotIzaDaemonApp *-- DotIzaDaemonDomain
    DotIzaIntegralApp *-- ModuleApp
    DotIzaIntegralApp *-- DotIzaDaemonApp
    component ModuleAppHashSetImpl
    node DotIzaDaemonAppLocalYamlFileImpl
    note top of DotIzaDaemonAppLocalYamlFileImpl: Output Module into Local Yaml File Daemon App
    ModuleAppHashSetImpl *-- ModuleApp
    DotIzaDaemonAppLocalYamlFileImpl *-- DotIzaDaemonApp
    ModuleAppHashSetImpl *-- LogAppSimpleImpl
    DotIzaDaemonAppLocalYamlFileImpl *-- LogAppSimpleImpl
    component ModuleAppTestImpl
    component DotIzaDaemonAppTestImpl
    component DotIzaIntegralAppTestImpl
    ModuleAppTestImpl *-- ModuleApp
    DotIzaDaemonAppTestImpl *-- DotIzaDaemonApp
    DotIzaIntegralAppTestImpl *-- DotIzaIntegralApp
    package DotIzaAppTests {
        component ModuleAppTest
        component DotIzaDaemonAppTest
        component DotIzaIntegralAppTest
    
        ModuleAppTest *-- ModuleAppTestImpl
        DotIzaDaemonAppTest *-- DotIzaDaemonAppTestImpl
        DotIzaIntegralAppTest *-- DotIzaIntegralAppTestImpl
    }
    
    
    package LibIza {
        cloud PackageDomain
        cloud ResourceDomain
    
        PackageDomain *-- ResourceDomain
        PackageDomain *-- ModuleApp
        PackageDomain *-- LogApp
        ResourceDomain *-- ModuleApp
        ResourceDomain *-- LogApp
    }
    interface PackageApp
    interface ResourceApp
    interface LibIzaIntegralApp
    PackageApp *-- PackageDomain
    ResourceApp *-- ResourceDomain
    LibIzaIntegralApp *-- PackageApp
    LibIzaIntegralApp *-- ResourceApp
    node PackageAppExeImpl
    node ResourceAppExeImpl
    note top of PackageAppExeImpl: Package App for iza executable
    note top of ResourceAppExeImpl: Resource App for iza executable
    PackageAppExeImpl *-- PackageApp
    ResourceAppExeImpl *-- ResourceApp
    PackageAppExeImpl *-- ModuleAppHashSetImpl
    ResourceAppExeImpl *-- ModuleAppHashSetImpl
    PackageAppExeImpl *-- LogAppSimpleImpl
    ResourceAppExeImpl *-- LogAppSimpleImpl
    component PackageAppTestImpl
    component ResourceAppTestImpl
    component LibIzaIntegralAppTestImpl
    PackageAppTestImpl *-- PackageApp
    ResourceAppTestImpl *-- ResourceApp
    LibIzaIntegralAppTestImpl *-- LibIzaIntegralApp
    package LibIzaAppTests {
        component PackageAppTest
        component ResourceAppTest
        component LibIzaIntegralAppTest
    
        PackageAppTest *-- PackageAppTestImpl
        ResourceAppTest *-- ResourceAppTestImpl
        LibIzaIntegralAppTest *-- LibIzaIntegralAppTestImpl
    }
}


frame iza {
    node iza_package
    node iza_package_new
    node iza_package_remove
    node iza_package_add_command
    node iza_package_add_file
    node iza_executor
    node iza_executor_new
    node iza_executor_remove
    node iza_fetcher
    node iza_fetcher_new
    node iza_fetcher_remove
    node iza_shifter
    node iza_shifter_new
    node iza_shifter_remove
    node iza_command
    node iza_command_new
    node iza_command_remove
    node iza_file
    node iza_file_new
    node iza_file_remove
    node iza_deploy
}

note top of iza_package: Show Package List
note top of iza_package_new: New Package
note top of iza_package_remove: Remove Package
note top of iza_package_add_command: Add Command into Package
note top of iza_package_add_file: Add File into Package
note top of iza_executor: Show Executor List
note top of iza_executor_new: New Executor
note top of iza_executor_remove: Remove Package
note top of iza_fetcher: Show Fetcher List
note top of iza_fetcher_new: New Fetcher
note top of iza_fetcher_remove: Remove Fetcher
note top of iza_shifter: Show Shifter List
note top of iza_shifter_new: New Shifter
note top of iza_shifter_remove: Remove Shifter
note top of iza_command: Show Command List
note top of iza_command_new: New Command
note top of iza_command_remove: Remove Command
note top of iza_file: Show File List
note top of iza_file_new: New File
note top of iza_file_remove: Remove File
note top of iza_deploy: Iza Deploy

@enduml