@startuml
title New Executor
autonumber

boundary ExecutorApp
entity Executor
database ExecutorRepository

box PackageDomain
    participant ExecutorApp
    participant Executor
    participant ExecutorRepository
end box

ExecutorApp --> Executor : ExecutorName
ExecutorApp <-- Executor : Arc<Executor>
ExecutorApp --> ExecutorRepository : Arc<Executor>
ExecutorApp <-- ExecutorRepository : Arc<Executor>

@enduml